### PR TITLE
Fix Page-Nav example 1 is broke

### PR DESCRIPTION
**Pull request by ghost**
## Type of change

- [X] Bug Fix
- [ ] New Feature
- [ ] Refactor
- [ ] Project Build
- [ ] Project Configuration

## Submission Checklist

- [X] Have you followed the guidelines in our [Contributing document](https://github.com/fanappics/buoy/blob/master/CONTRIBUTING.md)?
- [ ] Did you create appropriate tests? 

Thinking of: https://github.com/Huddle/Resemble.js

## Description

BPageNave first example was broken:
screen shot 2018-02-16 at 8 12 41 am

## Related Issues / Bugs / Feature Requests

https://jira.fanatics.com/browse/CPDT-131

## Test Deployment URL

https://rawgit.com/fanappics/buoy/bf-cpdt-131/docs/index.html#bpagenav

## Deployment Notes

Notes regarding deployment the contained body of work.  These should note any
db migrations, etc.

## Steps to Test or Reproduce

- look at styleguide in master
- look at styleguide on this branch:
screen shot 2018-02-16 at 9 51 27 am

### CODE REVIEW

**Review by fobesjason — CHANGES_REQUESTED** [review]
One of the examples was supposed to show the horizontal page nav option.  Are they both vertical page navs now?

**Review by fobesjason — APPROVED** [review]

**Comment by eleanormal** [comment]
The example no longer shows the "finished" indicators

**Comment by kierachell** [comment]
did it ever?

**Comment by eleanormal** [comment]
In your first screenshot it does at least show the spaces for the indicators. And when the PageNav was initially created, yet, it showed the finished indicator otherwise it would not have been approved.

**Comment by kierachell** [comment]
I can't find it:
screen shot 2018-02-19 at 8 58 39 am

**Comment by eleanormal** [comment]
I see the problem. Chrome is blocking the ionic css from importing because it's HTTP instead of HTTPS.

**Review by elemjay19 — APPROVED** [review]

**Pull request merged**
